analyzer:
linter:
  rules:
    - annotate_overrides
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_empty_else
    - avoid_field_initializers_in_const_classes
    - avoid_init_to_null
    - avoid_relative_lib_imports
    - avoid_returning_null
    - avoid_returning_null_for_void
    - avoid_return_types_on_setters
    - avoid_returning_null_for_future
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - await_only_futures
    - cascade_invocations
    - camel_case_types
    - curly_braces_in_flow_control_structures
    - constant_identifier_names
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - file_names
    - implementation_imports
    - join_return_with_assignment
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - non_constant_identifier_names
    - null_closures
    - overridden_fields
    - prefer_adjacent_string_concatenation
    - prefer_contains
    - prefer_conditional_assignment
    - prefer_collection_literals
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_locals
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_equal_for_default_values
    - prefer_int_literals
    - prefer_mixin
    - prefer_null_aware_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - prefer_iterable_whereType
    - recursive_getters
    - slash_for_doc_comments
    - type_init_formals
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_brace_in_string_interps
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_function_type_syntax_for_parameters
    - use_to_and_as_if_applicable
    - use_rethrow_when_possible
    - valid_regexps
    - void_checks
    - sort_pub_dependencies
    - package_names